// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // TODO(Lyokone): Remove when FlutterFire CLI updated
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC90U_qTTsJdCDDvmFflZhJBPlW-apsY2g',
    appId: '1:642051318446:web:87e25e51afe982cd3574d0', // Derived from project number
    messagingSenderId: '642051318446',
    projectId: 'smridge-a1203',
    authDomain: 'smridge-a1203.firebaseapp.com',
    storageBucket: 'smridge-a1203.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC90U_qTTsJdCDDvmFflZhJBPlW-apsY2g',
    appId: '1:642051318446:android:3c310522cbc9f3b2cb033f',
    messagingSenderId: '642051318446',
    projectId: 'smridge-a1203',
    storageBucket: 'smridge-a1203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90U_qTTsJdCDDvmFflZhJBPlW-apsY2g',
    appId: '1:642051318446:ios:acd9c8e17b5e620e3574d0', // Derived from project number
    messagingSenderId: '642051318446',
    projectId: 'smridge-a1203',
    storageBucket: 'smridge-a1203.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90U_qTTsJdCDDvmFflZhJBPlW-apsY2g',
    appId: '1:642051318446:ios:acd9c8e17b5e620e3574d0', // Derived from project number
    messagingSenderId: '642051318446',
    projectId: 'smridge-a1203',
    storageBucket: 'smridge-a1203.firebasestorage.app',
  );
}
